### ISSUE TITLE
Move Search with Icon to nav menu

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/circus#17]
As discussed with LD 2020-02-13: Move the search link to the header nav menu. Since there's no input box (it's just a simple link), it makes most sense to place in the header with the rest of the navigation items. 

This means it should go in the footer, too.

**Comment by ubermichael** [comment]
The menus are defined by some code in Symfony. I can add that search thing very easily.

**Comment by joeytakeda** [comment]
Sure! Did you want to hop into my branch or do it in your own?
