### ISSUE TITLE
Display a more meaningful field instead of camera-assigned filename

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/circus#20]
**Describe the bug**
All clippings are labelled by the camera-assigned file name. I'm not entirely sure that this is a bug, but it seems like it might be? On the home page, the camera-assigned file name is under the image below the gallery. 

**To Reproduce**
Steps to reproduce the behavior on the home page:
1. Go to Circus home page
2. See error.

Steps to reproduce the behavior on the Clippings page:
1. Go to Clippings page
2. See error

**Expected behavior**
Not sure if this is an error!

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by joeytakeda** [comment]
Agreed that the image name probably isn't the most useful thing to display; we'll have to ask the PI what could be used instead. My vote is for using the simple clipping id (i.e. Clipping Details: Clipping 22) if there is no better title.

**Comment by ubermichael** [comment]
Looks done to me!
