### ISSUE TITLE
Eliminate Dropdown Menu under Clippings

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/circus#21]
**Describe the bug**
Dropdown under 'Clippings' that only has 'Clippings' in it.

**To Reproduce**
1. Go to Circus home page
2. Click 'Clippings'
3. See error

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by joeytakeda** [comment]
Note that if you login, you get two additional categories: Categories and Sources, both of which are helpful ways to organize the data. 

I'm not sure why these are behind the login screen, though--I think they ought to be added to the public view since they are helpful ways to navigate the data.

**Comment by ubermichael** [comment]
No longer an issue. Thanks Joey!
