### ISSUE TITLE
Enable better paging system for Clippings results  

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/circus#23]
**Is your feature request related to a problem? Please describe.**
Right now, when you're on every clippings page, you see "Displaying 25 clippings of 2948 total."

**Describe the solution you'd like**
It would be really great to make this clearer for users!

**Describe alternatives you've considered**
"Displaying 1 - 25 clippings of 2948 total" and then "Displaying 26 - 50 clippings of 2948 total"

**Comment by ubermichael** [comment]
The pagination info in the header is gone now, so this isn't an issue anymore.
