### ISSUE TITLE
'Created by...' on About and Bib pages

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/circus#25]
**Describe the bug**
There's a 'created by Michael Joyce' on the About and Bib pages. Not sure if this is a bug, but seems like it shouldn't be there!

**To Reproduce**
1. Go to About page
2. See error

1. Go to Bib page
2. See error

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Additional context**
This also has nothing to do with anything, really, but is the paragraph on the bib page the only thing that's going to be there? If so, we should consider changing this. It's misleading!

**Comment by joeytakeda** [comment]
This is now fixed: The created on bit is only shown for logged in users; otherwise, it's hidden.
