### ISSUE TITLE
Paging mechanism produces an error message

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/circus#32]
When navigating to this page: https://dhil.lib.sfu.ca/circus/clipping/?page=5

We're getting:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by ubermichael** [comment]
It isn't the paging mechanism, it's a file permission issue in the logs directory. I've asked the systems folks to take a look at it.

**Comment by ubermichael** [comment]
Should be fixed now.
